theme: jekyll-theme-slate

# Name of website
title: Powering Potential 2019 - Human Genomics in NZ

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Miles Benton

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "miles.benton@esr.cri.nz"
  github: sirselim
  twitter: miles_benton